In [3]:
import numpy as np 
#default value is float

In [ ]:
A1 = np.array([1, 2, 3, 4])
print(A1)
type(A1)
A1.shape

In [21]:
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(A2)
A2.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [22]:
A3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(A3)
print(A3.shape)
A3.size

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


12

In [ ]:
z1 = np.zeros(3, dtype=int)
z1

In [ ]:
z2 = np.zeros((3, 4), dtype=int)
z2

In [ ]:
#amounts: array, columns, rows
z3 = np.zeros((2, 3, 4), dtype=int)
z3

In [4]:
#full array default value is integer
f1 = np.full(3, 55)
print(f1)

[55 55 55]


In [24]:
f2 = np.full((2, 3), 67)
print(f2)

[[67 67 67]
 [67 67 67]]


In [23]:
f3 = np.full((2, 3, 4), "Python")
print(f3)
np.ndim(f3)

[[['Python' 'Python' 'Python' 'Python']
  ['Python' 'Python' 'Python' 'Python']
  ['Python' 'Python' 'Python' 'Python']]

 [['Python' 'Python' 'Python' 'Python']
  ['Python' 'Python' 'Python' 'Python']
  ['Python' 'Python' 'Python' 'Python']]]


3

numpy random module:

In [ ]:
from numpy import random

np.random.random()

In [38]:
#default value: float. 
#generates random floating numbers in the range[0.1, 1.0)
#
r1 = np.random.random(3)
print(r1)
r2 = np.random.random((2, 3, 5))
print(r2)

[0.33636409 0.77567089 0.08082378]
[[[0.81852446 0.15748249 0.76047006 0.89172911 0.4095427 ]
  [0.76768071 0.9900526  0.11033373 0.77730358 0.21440735]
  [0.17012405 0.84192019 0.52033113 0.01187458 0.82540547]]

 [[0.54064803 0.44808809 0.38091636 0.2159958  0.98797224]
  [0.05274698 0.12983102 0.81244954 0.16524289 0.29499924]
  [0.13957497 0.70073853 0.61712162 0.33320029 0.02072831]]]


In [45]:
#range min, range max, needed amount
np.random.randint(2, 13, 5)

array([ 8, 12,  7,  2, 10])

In [46]:
#randn returns float numbers in random both negative and positive
#in form of array
np.random.randn(4)

array([-1.16802835, -0.08399547, -1.52151721,  0.00348471])

In [19]:
#range, range max, necessary amount
np.random.uniform(1, 4, 10)

array([2.71222171, 1.27295358, 3.12733147, 1.63033463, 1.56176119,
       2.48540079, 2.21266377, 1.57237399, 1.00484266, 2.06576367])

In [51]:
#selg¿f explanatory title
np.random.choice([2, 4, 6, 3, 1, 65, 87, 9])

np.random.choice([2, 4, 6, 3, 1, 65, 87, 9], 4)

array([ 4,  4, 87,  4])

In [13]:
np.random.choice(21, 30)
#replace means repeat numbers, set to false means no repeated numbers
np.random.choice([2, 4, 6, 3, 1, 65, 87, 9], size=7, replace=False)

array([ 4, 65,  2,  6,  1, 87,  9])

In [57]:
#returns evenly spaced values
#start value, end value and numbers needed
A = np.linspace(2, 20, num=10)
print(A)
#endpoint= False if we don't want "20" to show: num=10, endpoint=False
#retstep shows spacing betwen values


[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [ ]:
#all possible linearly distributed values
A = np.linspace(2, 20)
print(A)

In [68]:
a = np.empty(5, dtype=object)
print(a)

b = np.empty((5, 3), dtype=int)
print(b)
#can create arbitrary numbers

[None None None None None]
[[      0       0       0]
 [      0       0       0]
 [      0       0       0]
 [      0    1656       0]
 [      0 6357091       0]]


In [ ]:
#k is index of diagonal
b = np.eye(4, k=1)
print(b)
print("\n")
c = np.eye(4)
print(c)
print("\n")
d = np.eye(4, k=-2)
print(d)
print("\n")
e = np.eye(5, dtype=str)
print(e)

In [35]:
# identity matrix a square matrix with 1s on main diagonal
# change number to 21
A = np.identity(4, dtype=int)
B = A * 21
print(A)
print("\n")
print(B)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


[[21  0  0  0]
 [ 0 21  0  0]
 [ 0  0 21  0]
 [ 0  0  0 21]]


In [33]:
#simple 1D array
B = np.array([1, 2, 3, 4, 5])
np.diag(B, k=0)

1

In [31]:
#cna't use diag on 3D array, 3D array is made with two pairs: [[]] plus
#each [] that the values require eg: [[[1, 2, 3], [4, 5, 6]]]
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
np.diag(A, k=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 6])