In [1]:
import numpy as np 
#default value is float

In [ ]:
A1 = np.array([1, 2, 3, 4])
print(A1)
type(A1)
A1.shape

In [ ]:
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(A2)
A2.ndim

In [ ]:
A3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(A3)
print(A3.shape)
A3.size

In [ ]:
z1 = np.zeros(3, dtype=int)
z1

In [ ]:
z2 = np.zeros((3, 4), dtype=int)
z2

In [ ]:
#amounts: array, columns, rows
z3 = np.zeros((2, 3, 4), dtype=int)
z3

In [ ]:
#full array default value is integer
f1 = np.full(3, 55)
print(f1)

In [ ]:
f2 = np.full((2, 3), 67)
print(f2)

In [ ]:
f3 = np.full((2, 3, 4), "Python")
print(f3)

numpy random module:

In [41]:
from numpy import random

np.random.random()

0.28330767478314134

In [ ]:
r1 = np.random.random(3)
print(r1)
r2 = np.random.random((2, 3, 5))
print(r2)

In [45]:
#range min, range max, needed amount
np.random.randint(2, 13, 5)

array([ 8, 12,  7,  2, 10])

In [46]:
#randm returns float numbers in random both negative and positive
#in form of array
np.random.randn(4)

array([-1.16802835, -0.08399547, -1.52151721,  0.00348471])

In [48]:
np.random.uniform(1, 4, 10)

array([2.72594729, 3.05553141, 3.66364118, 1.19788202, 1.80444956,
       1.4442469 , 1.6451351 , 1.71701857, 3.69680854, 1.03739982])

In [51]:
np.random.choice([2, 4, 6, 3, 1, 65, 87, 9])

np.random.choice([2, 4, 6, 3, 1, 65, 87, 9], 4)

array([ 4,  4, 87,  4])

In [53]:
np.random.choice(21, 30)
#replace means repeat numbers, set to false means no repeated numbers
np.random.choice([2, 4, 6, 3, 1, 65, 87, 9], size=7, replace=False)

array([20,  6,  6,  6, 13,  9, 17, 10,  2,  3,  9, 20, 17, 19,  8,  2,  5,
        7,  5,  1, 15,  3, 13, 20, 16, 10,  7, 19,  3, 20])

In [57]:
#returns evemly spaced values
#start value, end value and numbers needed
A = np.linspace(2, 20, num=10)
print(A)
#endpoint= False if we don't want "20" to show: num=10, endpoint=False
#retstep shows spacing betwen values


[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [ ]:
#all possible linearly distributed values
A = np.linspace(2, 20)
print(A)

In [68]:
a = np.empty(5, dtype=object)
print(a)

b = np.empty((5, 3), dtype=int)
print(b)
#can create arbitrary numbers

[None None None None None]
[[      0       0       0]
 [      0       0       0]
 [      0       0       0]
 [      0    1656       0]
 [      0 6357091       0]]


In [ ]:
#k is index of diagonal
b = np.eye(4, k=1)
print(b)
print("\n")
c = np.eye(4)
print(c)
print("\n")
d = np.eye(4, k=-2)
print(d)
print("\n")
e = np.eye(5, dtype=str)
print(e)

In [ ]:
A = np.identity(4, dtype=int)
B = A * 21
print(A)
print("\n")
print(B)


In [88]:
B = np.array([1, 2, 3, 4, 5])
np.diag(B, k=0)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [87]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
np.diag(A, k=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 6])